@baseUrl = http://localhost:3000

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@email.dev",
  "password": "theuserpassword"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/1

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Some user",
  "email": "someuser@email.com",
  "password": "averysecurepassword"
}